### ISSUE TITLE
Option for manual console flushing and passing the console into SPECS world

### ISSUE THREAD

**Issue by uzkbwza** [thebracket/rltk_rs#29]
My apologies if this is already possible.

One of the really nice things about SPECS is its automatic handling of parallelization. in my current (spaghetti code) project, I have a "rendering system" using tcod running on its own thread. Instead of calling render functions during the top-level game loop, I control exactly when it updates the game view, and because it is running concurrently, it does not need to wait for an entire game tick to finish (nor do other systems need to wait for it) in order to render. the console is simply a resource in the SPECS world that the rendering system (and possible other systems) gets mutable access to.

unfortunately, when I tried moving my project to use this (more fully-featured, modern, and native-feeling) library, I ran into the issue wherein I must wait for _every system_ in the game to stop before flushing to the console (and vice versa), since I had to move the rendering logic into the `tick()` function for the `State` implementation. this moved the entire system outside of the SPECS world and into its own separate process which ran after every world update, slowing things down. It has been a little while since then, but I recall not being able to figure out how I would call the rendering functions from a system in the world.

I'm not a very good programmer, and so maybe there are ways i'm not seeing around this by writing my own multi-threaded implementation, but either way it adds some complexity to my project where there wasn't any before. i'd like to hear what your thoughts are on this, if there is some part of the rltk-rs I missed that takes care of this, and if the architecture of the library could support something along these lines.

**Comment by thebracket** [comment]
It will require a bit of architecture changing, but I think it's a good idea to have a better way to expose RLTK to your underlying system (it doesn't require that you're using Specs, and you might be in Amethyst, curses or GL!) to grant some more rendering control. It is *tricky* to mesh the two, so I'll keep this issue up to remind me to come up with a better way.

The root issue is that RLTK doesn't require you to use Specs, but does take over the render loop (so you wind up feeding render updates into RLTK after your systems run, as you saw). I'm reluctant to make everyone use specs, but it's probably possible to offer an alternate "way in" (that is thread happy; that's tricky because I have to also support WASM which doesn't do threading yet) to send updates.

Amethyst does a good job of having you update the components and it renders them - although it is coalescing your render state at the end of a frame, too - it just hides it better!

**Comment by thebracket** [comment]
The new `command_buffer` system helps with this. You can request a buffer from inside a Specs system, and draw to it. You lose the ability to query the existing display buffer, but very little code does this).  It then batches the draws at the end. I've updated the `specs` example to demonstrate how to use this.

**Comment by thebracket** [comment]
The improvements are in the following commits:

* https://github.com/thebracket/rltk_rs/commit/f70087dd261d47bb073f9844e0b6fc93f8d81015#diff-b1f2b69f8aa3303e8441f523c6e019ae
* https://github.com/thebracket/rltk_rs/commit/8dbb7786bc65d427b13295e073c6aeb2a28d6fc3#diff-b1f2b69f8aa3303e8441f523c6e019ae
* https://github.com/thebracket/rltk_rs/commit/cb28eb53daabce5cd3af22d16cfd325f3eeec8ae#diff-b1f2b69f8aa3303e8441f523c6e019ae
* https://github.com/thebracket/rltk_rs/commit/c1d2556d742b3017bd0614b2c55aacd56785cc39#diff-b1f2b69f8aa3303e8441f523c6e019ae
* https://github.com/thebracket/rltk_rs/commit/c1d2556d742b3017bd0614b2c55aacd56785cc39#diff-b1f2b69f8aa3303e8441f523c6e019ae
* https://github.com/thebracket/rltk_rs/commit/c0a79e5d9c9ccb42b9c56cdc7dba12afe048b61d#diff-b1f2b69f8aa3303e8441f523c6e019ae
* https://github.com/thebracket/rltk_rs/commit/d4a0ce850fa6223b4b190dfc2969bc707e0c4266#diff-b1f2b69f8aa3303e8441f523c6e019ae

(Because I forgot to tag them)
