### ISSUE TITLE
Crossterm back-end

### ISSUE THREAD

**Issue by thebracket** [thebracket/rltk_rs#63]
It might be nice to support crossterm, it's a bit easier to work with than pancurses.

**Comment by erlend-sh** [comment]
cc @timonpost

**Comment by TimonPost** [comment]
It sounds like a great idea! You might even consider using my new crate https://github.com/crossterm-rs/terminal. Which wraps 3 backends optional (termion, pancurses, crossterm) behind one interface. It is quite new and unstable so that might be a factor to not use this library and use crossterm on its own instead.

**Comment by thebracket** [comment]
Wow, the terminal wrapper looks great! I'm playing with some basic support of just crossterm right now, but it wouldn't be hard to port once I've finished getting a feel for working with the library. So far it looks great, btw - thanks!

**Comment by TimonPost** [comment]
If there are any questions please let me know! You can join the crossterm discord for faster support...

**Comment by thebracket** [comment]
Progress is in this branch: https://github.com/thebracket/rltk_rs/tree/crossterm
Output is working, plugging away on input.

**Comment by thebracket** [comment]
It needs a *lot* of tidying up and input support, but not a bad afternoon on this:
![crosstermwalking](https://user-images.githubusercontent.com/14896751/73490599-78308580-4372-11ea-840a-e3964530830c.gif)
